#!/usr/bin/env python3
"""Export the coarse Model-0 state and reaction curve from the T7 online path.

The path uses the same standard-FE continuation and Reduced-NE settings as
``model0_online_reference_free_h005_peak_v1``.  It writes a compact CSV for
the reaction curve and one VTU file containing the accepted final phase field.
This ``h=0.05`` export supports solver-mechanism diagnostics; the resolved
physical reference path is generated by ``run_model0_fine_reference.py``.

Usage
-----
python scripts/paper_solver/export_model0_online_state.py \
    --output-dir results/phasefield_solver/model0_example_reference_free_h005_full_v1/online_export
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import numpy as np


SCRIPT_VERSION = "1.0"
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = PROJECT_ROOT.parent / "results/phasefield_solver/model0_example_reference_free_h005_full_v1/online_export"


def _verification_args() -> argparse.Namespace:
    """Build the exact reproducible T7 Model-0 verification arguments."""
    from scripts.paper_solver import verify_slow_mode_fracturex as verify

    argv = [
        "verify_slow_mode_fracturex.py",
        "--case", "model0_example",
        "--mesh-size", "0.05",
        "--seed", "0",
        "--max-iterations", "2000",
        "--phase-active-set-max-iterations", "1000",
        "--theta", "0.7",
        "--slow-relative-radius", "0.9",
        "--online-increment-windows", "3,4,5",
        "--online-relative-singular-value", "0.01",
        "--online-max-dimension", "4",
        "--online-solver-window", "5",
        "--history-survival-loads", "0.125",
        "--reduced-solver",
        "--reduced-patches", "online",
        "--reduced-patch-space", "coupled",
        "--reduced-warmup-sweeps", "100",
        "--reduced-solver-loads", "0.125",
        "--reduced-max-outer-iterations", "20",
        "--reduced-max-krylov-iterations", "160",
        "--reduced-krylov-rtol", "0.0001",
        "--reduced-fd-step", "0.000001",
        "--reduced-reference-free-acceptance",
        "--reduced-reference-free-state-tolerance", "5e-7",
        "--reduced-reference-free-condition-scaled-residual-tolerance", "3e-3",
    ]
    saved_argv = sys.argv
    sys.argv = argv
    try:
        return verify._parse_args()
    finally:
        sys.argv = saved_argv


def _write_vtu(path: Path, nodes: np.ndarray, cells: np.ndarray, damage: np.ndarray) -> None:
    """Write triangular FE nodes, connectivity, and pointwise damage to VTU."""
    import vtk
    from vtk.util.numpy_support import numpy_to_vtk

    points = vtk.vtkPoints()
    points.SetNumberOfPoints(nodes.shape[0])
    for index, point in enumerate(nodes):
        points.SetPoint(index, float(point[0]), float(point[1]), 0.0)

    grid = vtk.vtkUnstructuredGrid()
    grid.SetPoints(points)
    for cell in cells:
        triangle = vtk.vtkTriangle()
        for local, node in enumerate(cell):
            triangle.GetPointIds().SetId(local, int(node))
        grid.InsertNextCell(triangle.GetCellType(), triangle.GetPointIds())

    damage_array = numpy_to_vtk(np.asarray(damage, dtype=np.float64), deep=True)
    damage_array.SetName("damage")
    grid.GetPointData().AddArray(damage_array)
    writer = vtk.vtkXMLUnstructuredGridWriter()
    writer.SetFileName(str(path))
    writer.SetInputData(grid)
    if writer.Write() != 1:
        raise RuntimeError(f"failed to write VTU: {path}")


def export_model0(output_dir: Path) -> tuple[Path, Path]:
    """Run the T7 path and export its reaction curve and accepted final state."""
    from fealpy.backend import backend_manager as bm
    from scripts.paper_solver import verify_slow_mode_fracturex as verify

    args = _verification_args()
    main, step_map = verify._build_standard_fe_map(args)
    loads = np.concatenate(
        (
            np.linspace(0.0, 70.0e-3, 6, dtype=np.float64),
            np.linspace(70.0e-3, 125.0e-3, 26, dtype=np.float64)[1:],
        )
    )
    records: list[dict[str, object]] = [
        {
            "step": 0,
            "load": 0.0,
            "residual_force_abs": 0.0,
            "staggered_iterations": 0,
            "algorithm_stage": "initial",
        }
    ]

    def refresh_reaction() -> float:
        """Evaluate reaction after the accepted displacement correction."""
        main.H = bm.asarray(step_map.committed_history, dtype=main.d.dtype).copy()
        main.pfcm.update_historical_field(main.H)
        main.solve_displacement()
        main.solve_phase_field()
        return abs(float(np.asarray(bm.to_numpy(main._Rfu))))

    # Continue only through the pre-Reduced-NE state. The final load is passed
    # directly to _run_checkpoint below so its committed lower bound remains
    # the preceding converged state rather than the final state itself.
    for index, load in enumerate(loads[1:-1], start=1):
        step_map.set_load(float(load))
        step_map.history_snapshots.clear()
        step_map.record_history = False
        trace = verify.iterate_fixed_point(
            step_map,
            step_map.committed_damage,
            atol=float(args.atol),
            rtol=float(args.rtol),
            max_iterations=int(args.max_iterations),
        )
        if not trace.converged:
            raise RuntimeError(
                f"standard continuation did not converge at load {load:.8g}"
            )
        step_map(trace.solution)
        accepted_damage = trace.solution.copy()
        history = np.asarray(bm.to_numpy(main.H), dtype=np.float64).copy()
        reaction = refresh_reaction()
        step_map.commit_checkpoint(accepted_damage, history)
        records.append(
            {
                "step": index,
                "load": float(load),
                "residual_force_abs": reaction,
                "staggered_iterations": int(trace.iterations),
                "algorithm_stage": "staggered_continuation",
            }
        )
    # Run the final checkpoint through the actual diagnostic and Reduced-NE
    # path. The accepted reduced state is equal to this reference state within
    # the solver acceptance tolerance; _run_checkpoint restores that state.
    step_map.set_load(float(loads[-1]))
    final_summary, accepted_damage, _, _ = verify._run_checkpoint(main, step_map, args)
    reduced_summary = final_summary.get("reduced_nonlinear_solver")
    online_summary = (
        reduced_summary.get("patches", {}).get("online")
        if isinstance(reduced_summary, dict)
        else None
    )
    if not reduced_summary or not isinstance(online_summary, dict):
        raise RuntimeError("the final export did not execute Reduced-NE")
    reliability_checks = (
        "projected_residual_converged",
        "same_discrete_solution",
        "reference_free_state_correction",
        "reference_free_condition_scaled_residual",
    )
    if not all(online_summary.get("acceptance_checks", {}).get(name, False) for name in reliability_checks):
        raise RuntimeError("the final Reduced-NE state failed the reliability checks")
    final_state = step_map.current_full_state()
    final_damage = np.asarray(accepted_damage, dtype=float)
    final_reaction = refresh_reaction()
    records.append(
        {
            "step": len(records),
            "load": float(loads[-1]),
            "residual_force_abs": final_reaction,
            "staggered_iterations": int(final_summary["fixed_point"]["iterations"]),
            "algorithm_stage": "reduced_ne_checkpoint",
        }
    )

    mesh = main.mesh
    nodes = np.asarray(bm.to_numpy(mesh.entity("node")), dtype=float)
    cells = np.asarray(bm.to_numpy(mesh.entity("cell")), dtype=np.int64)
    if nodes.shape[1] != 2 or cells.ndim != 2 or cells.shape[1] != 3:
        raise ValueError("Model-0 export expects a two-dimensional triangular mesh")
    if final_damage.size != nodes.shape[0]:
        raise ValueError("p=1 phase field must have one value per mesh node")

    output_dir.mkdir(parents=True, exist_ok=True)
    vtk_dir = output_dir / "vtk"
    vtk_dir.mkdir(parents=True, exist_ok=True)
    vtu_path = vtk_dir / "step_0030_load_1.250000e-01.vtu"
    _write_vtu(vtu_path, nodes, cells, final_damage)
    csv_path = output_dir / "residual_force_vs_displacement.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(records[0]))
        writer.writeheader()
        writer.writerows(records)
    (output_dir / "meta.json").write_text(
        json.dumps(
            {
                "script_version": SCRIPT_VERSION,
                "source": "model0_example_reference_free_h005_full_v1",
                "algorithm": "model0_example full load schedule with Reduced-NE at u=0.125",
                "mesh_size": 0.05,
                "phase_length_scale": 0.02,
                "mesh_to_length_scale_ratio": 2.5,
                "scope": "coarse solver-mechanism diagnostic",
                "load_count": len(records),
                "final_load": 0.125,
                "final_summary_status": final_summary["status"],
                "acceptance_checks": online_summary["acceptance_checks"],
                "reliability_acceptance_passed": True,
                "cost_screen_passed": bool(
                    online_summary["acceptance_checks"].get(
                        "lower_residual_equivalent_work", False
                    )
                ),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return csv_path, vtu_path


def _parse_args() -> argparse.Namespace:
    """Parse export destination."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    return parser.parse_args()


def main() -> None:
    """Export the actual T7 Model-0 reaction curve and final state."""
    args = _parse_args()
    csv_path, vtu_path = export_model0(args.output_dir.resolve())
    print(f"[{SCRIPT_VERSION}] wrote {csv_path}")
    print(f"[{SCRIPT_VERSION}] wrote {vtu_path}")


if __name__ == "__main__":
    main()
